### PR TITLE
Swift4.2

### PR DESCRIPTION
**Pull request by rizumi**
Support Swift4.2
@haranicle Plaese review.

### CODE REVIEW

**Comment by haranicle** [comment]
https://github.com/nohana/NohanaImagePicker/issues/107

**Comment by haranicle** [comment]
There are some warnings. Please fix it.
screen shot 2018-10-10 at 19 01 46

**Comment by haranicle** [comment]
Though we don't support cococapods, please update .swift-version file.

**Comment by rizumi** [comment]
@haranicle 
Thanks for review.
I fixed them. Please review once more.

**Comment by haranicle** [comment]
LGTM 🎉

**Pull request merged**
